# Generated by Django 5.1.5 on 2025-01-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_dependent"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
